name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Lint
        run: |
          yarn install --ignore-scripts --ignore-optional --frozen-lockfile --non-interactive
          yarn run lint
        env:
          CI: true
  firebase-tests:
    name: Tests with Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: davydka/firebase-action@master
        with:
          args: firebase emulators:exec --only firestore "yarn test:react"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
